version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/eventsdb
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
